import os
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription, ExecuteProcess
from launch.substitutions import LaunchConfiguration, FindExecutable
from launch_ros.actions import Node
from launch.launch_description_sources import PythonLaunchDescriptionSource
from ament_index_python.packages import get_package_share_directory
from launch.substitutions import PythonExpression
from launch.conditions import IfCondition, UnlessCondition


def generate_launch_description():
    # Map parameters - adjusted for 25-drone formation (Y: -20~55, Z: 10~26)
    map_size_x = LaunchConfiguration('map_size_x', default = 10.0)
    map_size_y = LaunchConfiguration('map_size_y', default = 80.0)
    map_size_z = LaunchConfiguration('map_size_z', default = 40.0)
    odom_topic = LaunchConfiguration('odom_topic', default = 'visual_slam/odom')

    map_size_x_cmd = DeclareLaunchArgument('map_size_x', default_value=map_size_x, description='Map size along x')
    map_size_y_cmd = DeclareLaunchArgument('map_size_y', default_value=map_size_y, description='Map size along y')
    map_size_z_cmd = DeclareLaunchArgument('map_size_z', default_value=map_size_z, description='Map size along z')
    odom_topic_cmd = DeclareLaunchArgument('odom_topic', default_value=odom_topic, description='Odometry topic')

    use_mockamap = LaunchConfiguration('use_mockamap', default=False) # map_generator or mockamap
    use_mockamap_cmd = DeclareLaunchArgument('use_mockamap', default_value=use_mockamap, description='Choose map type, map_generator or mockamap')

    use_dynamic = LaunchConfiguration('use_dynamic', default=False)
    use_dynamic_cmd = DeclareLaunchArgument('use_dynamic', default_value=use_dynamic, description='Use Drone Simulation Considering Dynamics or Not')

    # Map generator node
    map_generator_node = Node(
        package='map_generator',
        executable='random_forest',
        name='random_forest',
        output='screen',
        parameters=[
            {'map/x_size': 10.0},
            {'map/y_size': 80.0},
            {'map/z_size': 40.0},
            {'map/resolution': 0.1},
            {'ObstacleShape/seed': 1.0},
            {'map/obs_num': 0},  # No obstacles
            {'ObstacleShape/lower_rad': 0.5},
            {'ObstacleShape/upper_rad': 0.7},
            {'ObstacleShape/lower_hei': 0.0},
            {'ObstacleShape/upper_hei': 3.0},
            {'map/circle_num': 0},  # No circular obstacles
            {'ObstacleShape/radius_l': 0.7},
            {'ObstacleShape/radius_h': 0.5},
            {'ObstacleShape/z_l': 0.7},
            {'ObstacleShape/z_h': 0.8},
            {'ObstacleShape/theta': 0.5},
            {'sensing/radius': 5.0},
            {'sensing/rate': 1.0},
            {'min_distance': 1.2}
        ],
        condition = UnlessCondition(use_mockamap)
    )

    mockamap_node = Node(
        package='mockamap',
        executable='mockamap_node',
        name='mockamap_node',
        output='screen',
        remappings=[
            ('/mock_map', '/map_generator/global_cloud')
        ],
        parameters=[
            {'seed': 127},
            {'update_freq': 0.5},
            {'resolution': 0.1},
            {'x_length': 10},
            {'y_length': 80},
            {'z_length': 40},
            {'type': 1},
            {'complexity': 0.05},
            {'fill': 0.12},
            {'fractal': 1},
            {'attenuation': 0.1}
        ],
        condition = IfCondition(use_mockamap)
    )

    # Layer separation configuration for 25 drones
    # 25 drones = 5 layers (5 drones per layer)
    # Symmetric distribution: -1.0m, -0.5m, 0.0m, +0.5m, +1.0m
    LAYER_COUNT_25 = 5
    LAYER_OFFSET_25 = 0.5  # meters vertical separation per layer
    LAYER_CENTER_OFFSET_25 = -1.0  # Start offset to center the layers symmetrically

    # Drone configurations - 25 drones
    # Init: 5x5 Grid formation (FORMATION_25_A) - Y: 8~24m, Z: 10~26m
    # Target: Triangle formation (FORMATION_25_B) - Y: 14~40m, Z: 10~23m
    # Generated by Fair Hungarian Algorithm - Max distance: 16.20m, Avg: 11.92m
    drone_configs = [
        {'drone_id': 0, 'init_x': 3.0, 'init_y': 8.0, 'init_z': 10.0, 'target_x': 3.0, 'target_y': 20.7, 'target_z': 16.5},  # Distance: 14.27m
        {'drone_id': 1, 'init_x': 3.0, 'init_y': 12.0, 'init_z': 10.0, 'target_x': 3.0, 'target_y': 27.1, 'target_z': 13.3},  # Distance: 15.46m
        {'drone_id': 2, 'init_x': 3.0, 'init_y': 16.0, 'init_z': 10.0, 'target_x': 3.0, 'target_y': 30.3, 'target_z': 16.5},  # Distance: 15.71m
        {'drone_id': 3, 'init_x': 3.0, 'init_y': 20.0, 'init_z': 10.0, 'target_x': 3.0, 'target_y': 27.1, 'target_z': 10.1},  # Distance: 7.10m
        {'drone_id': 4, 'init_x': 3.0, 'init_y': 24.0, 'init_z': 10.0, 'target_x': 3.0, 'target_y': 36.7, 'target_z': 19.7},  # Distance: 15.98m
        {'drone_id': 5, 'init_x': 3.0, 'init_y': 8.0, 'init_z': 14.0, 'target_x': 3.0, 'target_y': 23.9, 'target_z': 13.3},  # Distance: 15.92m
        {'drone_id': 6, 'init_x': 3.0, 'init_y': 12.0, 'init_z': 14.0, 'target_x': 3.0, 'target_y': 23.9, 'target_z': 16.5},  # Distance: 12.16m
        {'drone_id': 7, 'init_x': 3.0, 'init_y': 16.0, 'init_z': 14.0, 'target_x': 3.0, 'target_y': 30.3, 'target_z': 13.3},  # Distance: 14.32m
        {'drone_id': 8, 'init_x': 3.0, 'init_y': 20.0, 'init_z': 14.0, 'target_x': 3.0, 'target_y': 33.5, 'target_z': 22.9},  # Distance: 16.17m
        {'drone_id': 9, 'init_x': 3.0, 'init_y': 24.0, 'init_z': 14.0, 'target_x': 3.0, 'target_y': 36.7, 'target_z': 22.9},  # Distance: 15.51m
        {'drone_id': 10, 'init_x': 3.0, 'init_y': 8.0, 'init_z': 18.0, 'target_x': 3.0, 'target_y': 17.5, 'target_z': 19.7},  # Distance: 9.65m
        {'drone_id': 11, 'init_x': 3.0, 'init_y': 12.0, 'init_z': 18.0, 'target_x': 3.0, 'target_y': 20.7, 'target_z': 19.7},  # Distance: 8.86m
        {'drone_id': 12, 'init_x': 3.0, 'init_y': 16.0, 'init_z': 18.0, 'target_x': 3.0, 'target_y': 23.9, 'target_z': 19.7},  # Distance: 8.08m
        {'drone_id': 13, 'init_x': 3.0, 'init_y': 20.0, 'init_z': 18.0, 'target_x': 3.0, 'target_y': 33.5, 'target_z': 16.5},  # Distance: 13.58m
        {'drone_id': 14, 'init_x': 3.0, 'init_y': 24.0, 'init_z': 18.0, 'target_x': 3.0, 'target_y': 33.5, 'target_z': 19.7},  # Distance: 9.65m
        {'drone_id': 15, 'init_x': 3.0, 'init_y': 8.0, 'init_z': 22.0, 'target_x': 3.0, 'target_y': 14.3, 'target_z': 22.9},  # Distance: 6.36m
        {'drone_id': 16, 'init_x': 3.0, 'init_y': 12.0, 'init_z': 22.0, 'target_x': 3.0, 'target_y': 17.5, 'target_z': 22.9},  # Distance: 5.57m
        {'drone_id': 17, 'init_x': 3.0, 'init_y': 16.0, 'init_z': 22.0, 'target_x': 3.0, 'target_y': 20.7, 'target_z': 22.9},  # Distance: 4.79m
        {'drone_id': 18, 'init_x': 3.0, 'init_y': 20.0, 'init_z': 22.0, 'target_x': 3.0, 'target_y': 30.3, 'target_z': 19.7},  # Distance: 10.55m
        {'drone_id': 19, 'init_x': 3.0, 'init_y': 24.0, 'init_z': 22.0, 'target_x': 3.0, 'target_y': 30.3, 'target_z': 22.9},  # Distance: 6.36m
        {'drone_id': 20, 'init_x': 3.0, 'init_y': 8.0, 'init_z': 26.0, 'target_x': 3.0, 'target_y': 23.9, 'target_z': 22.9},  # Distance: 16.20m
        {'drone_id': 21, 'init_x': 3.0, 'init_y': 12.0, 'init_z': 26.0, 'target_x': 3.0, 'target_y': 27.1, 'target_z': 22.9},  # Distance: 15.41m
        {'drone_id': 22, 'init_x': 3.0, 'init_y': 16.0, 'init_z': 26.0, 'target_x': 3.0, 'target_y': 27.1, 'target_z': 16.5},  # Distance: 14.61m
        {'drone_id': 23, 'init_x': 3.0, 'init_y': 20.0, 'init_z': 26.0, 'target_x': 3.0, 'target_y': 27.1, 'target_z': 19.7},  # Distance: 9.49m
        {'drone_id': 24, 'init_x': 3.0, 'init_y': 24.0, 'init_z': 26.0, 'target_x': 3.0, 'target_y': 39.9, 'target_z': 22.9},  # Distance: 16.20m
    ]

    drone_nodes = []

    for config in drone_configs:
        drone_launch = IncludeLaunchDescription(
            PythonLaunchDescriptionSource(
                os.path.join(get_package_share_directory('ego_planner'), 'launch', 'run_in_sim.launch.py')),
            launch_arguments={
                'drone_id': str(config['drone_id']),
                'init_x': str(config['init_x']),
                'init_y': str(config['init_y']),
                'init_z': str(config['init_z'] + LAYER_CENTER_OFFSET_25 + (config['drone_id'] % LAYER_COUNT_25) * LAYER_OFFSET_25),  # Symmetric layer separation
                'target_x': str(config['target_x']),
                'target_y': str(config['target_y']),
                'target_z': str(config['target_z']),
                'map_size_x': map_size_x,
                'map_size_y': map_size_y,
                'map_size_z': map_size_z,
                'odom_topic': odom_topic,
                'planning_horizon': '15.0'  # Increased from 7.5 to 15.0 for better pathfinding in dense swarms
                # Using minimal launch file - no visualization, no dynamics
            }.items()
        )
        drone_nodes.append(drone_launch)

    # Swarm Synchronizer - waits for all drones to spawn, then triggers start
    project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(
        get_package_share_directory('ego_planner')))))
    swarm_sync_script = os.path.join(project_root, 'scripts', 'swarm_synchronizer.py')

    swarm_synchronizer = ExecuteProcess(
        cmd=['python3', swarm_sync_script, '--ros-args', '-p', 'num_drones:=25', '-p', 'wait_time:=5.0'],
        output='screen'
    )

    # Mission Timer - tracks start time and arrival times
    mission_timer_script = os.path.join(project_root, 'scripts', 'mission_timer.py')

    # Build parameter list for mission timer
    timer_cmd = ['python3', mission_timer_script, '--ros-args', '-p', 'num_drones:=25', '-p', 'arrival_threshold:=0.5']
    for config in drone_configs:
        drone_id = config['drone_id']
        timer_cmd.extend([
            '-p', f'drone_{drone_id}_target_x:={config["target_x"]}',
            '-p', f'drone_{drone_id}_target_y:={config["target_y"]}',
            '-p', f'drone_{drone_id}_target_z:={config["target_z"]}'
        ])

    mission_timer = ExecuteProcess(
        cmd=timer_cmd,
        output='screen'
    )

    # Trajectory Recorder - automatically records all drone trajectories
    trajectory_recorder_node = Node(
        package='traj_recorder',
        executable='traj_recorder_node',
        name='trajectory_recorder',
        output='screen',
        parameters=[{
            'num_drones': 25,
            'output_folder': 'trajectories_25_drones',
            'sampling_dt': 0.02,  # 50Hz sampling
            'default_rgb': [255, 255, 255],
        }]
    )

    ld = LaunchDescription()

    # Add arguments
    ld.add_action(map_size_x_cmd)
    ld.add_action(map_size_y_cmd)
    ld.add_action(map_size_z_cmd)
    ld.add_action(odom_topic_cmd)
    ld.add_action(use_mockamap_cmd)
    ld.add_action(use_dynamic_cmd)

    # Add map nodes (disabled to reduce memory usage - trajectory visualization only)
    # ld.add_action(map_generator_node)
    # ld.add_action(mockamap_node)

    # Add swarm synchronizer (will exit after trigger) and mission timer
    ld.add_action(swarm_synchronizer)
    ld.add_action(mission_timer)

    # Add trajectory recorder
    ld.add_action(trajectory_recorder_node)

    # Add drone nodes
    for drone in drone_nodes:
        ld.add_action(drone)

    # Scenario publisher removed - using PRESET_TARGET mode with hardcoded assignments

    return ld
